# Generated by Django 3.2.12 on 2023-01-03 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.pollutant')),
            ],
        ),
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='airdata',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.city'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='pollutant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.pollutant'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.sensor'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('advice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.advice')),
            ],
        ),
        migrations.AddField(
            model_name='advice',
            name='prevention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.prevention'),
        ),
    ]
