# Generated by Django 3.2.12 on 2023-01-04 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air', '0002_auto_20230104_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ['pollutant'], 'verbose_name': 'Попередження по забруднику', 'verbose_name_plural': 'Попередження по забрудниках'},
        ),
        migrations.AlterModelOptions(
            name='airdata',
            options={'ordering': ['id'], 'verbose_name': 'Дані', 'verbose_name_plural': 'Дані'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['datetime'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='pollutant',
            options={'ordering': ['name'], 'verbose_name': 'Забрудник', 'verbose_name_plural': 'Забрудники'},
        ),
        migrations.AlterModelOptions(
            name='prevention',
            options={'ordering': ['id'], 'verbose_name': 'Попередження', 'verbose_name_plural': 'Попередження'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['kind', 'name'], 'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AddField(
            model_name='city',
            name='api_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва для API'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='api_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва для API'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='api_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва для API'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='pollutant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.pollutant', verbose_name='Забрудник'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='prevention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.prevention', verbose_name='Попередження'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор запису'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.city', verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='concentration',
            field=models.FloatField(null=True, verbose_name='Концентрація(мкг/м³)'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='pollutant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.pollutant', verbose_name='Забрудник'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.sensor', verbose_name='Датчик'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='news',
            name='advice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='air.advice', verbose_name='Попередження'),
        ),
        migrations.AlterField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата та час публікації'),
        ),
        migrations.AlterField(
            model_name='pollutant',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='pollutant',
            name='norm_ind',
            field=models.FloatField(null=True, verbose_name='Нормальний показник(мкг/м³)'),
        ),
        migrations.AlterField(
            model_name='prevention',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='kind',
            field=models.CharField(max_length=30, null=True, verbose_name='Вид датчику'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
    ]
